src/Entity/Guest.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GuestRepository")
 */
class Guest
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Project", mappedBy="guest" , cascade={"persist"})
     */
    private $projects;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $newsletter_is_active;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_coming;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $is_coming_with;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $vegetarian_meal_number;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $meat_meal_number;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="guests")
     */
    private $type;

    public function __toString()
    {
        return $this->lastname;
    }

    public function __construct()
    {

        $this->projects = new ArrayCollection();
        $this->created_at = new \DateTime;
        $this->updated_at = new \DateTime;
        $this->is_active = true;
        $this->newsletter_is_active = true;
        $this->is_coming = false;
        $this->phone_number = 'non remplis';
        $this->email = 'non remplis';
        $this->vegetarian_meal_number = 0;
        $this->meat_meal_number = 0;
        $this->is_coming_with = 1;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->addGuest($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->contains($project)) {
            $this->projects->removeElement($project);
            $project->removeGuest($this);
        }

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getNewsletterIsActive(): ?bool
    {
        return $this->newsletter_is_active;
    }

    public function setNewsletterIsActive(?bool $newsletter_is_active): self
    {
        $this->newsletter_is_active = $newsletter_is_active;

        return $this;
    }

    public function getIsComing(): ?bool
    {
        return $this->is_coming;
    }

    public function setIsComing(?bool $is_coming): self
    {
        $this->is_coming = $is_coming;

        return $this;
    }
    
    public function getIsComingWith(): ?int
    {
        return $this->is_coming_with;
    }

    public function setIsComingWith(?int $is_coming_with): self
    {
        $this->is_coming_with = $is_coming_with;

        return $this;
    }

    public function getVegetarianMealNumber(): ?int
    {
        return $this->vegetarian_meal_number;
    }

    public function setVegetarianMealNumber(?int $vegetarian_meal_number): self
    {
        $this->vegetarian_meal_number = $vegetarian_meal_number;

        return $this;
    }

    public function getMeatMealNumber(): ?int
    {
        return $this->meat_meal_number;
    }

    public function setMeatMealNumber(?int $meat_meal_number): self
    {
        $this->meat_meal_number = $meat_meal_number;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/ApiType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

class ApiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
           
           
        ->add('password', RepeatedType::class, [
            'label' => 'Mot de passe',
            'type' => PasswordType::class,
            'invalid_message' => 'The password fields must match.',
            'options' => ['attr' => ['class' => 'password-field']],
            'required' => true,
            'first_options'  => [
                'label' => 'Nouveau mot de passe',
            ],
            'second_options' => [
                'label' => 'Confirmation',
            ],
        ]);
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Api/ApiController.php
<?php

namespace App\Controller\Api;

use DateTime;
use App\Entity\Role;
use App\Entity\User;
use App\Entity\Guest;
use App\Entity\Image;
use App\Form\ApiType;
use Firebase\JWT\JWT;
use App\Form\ApiType2;
use App\Entity\Project;
use App\Form\GuestType;
use App\Repository\RoleRepository;
use App\Repository\TypeRepository;
use App\Repository\UserRepository;
use App\Repository\GuestRepository;
use App\Repository\ImageRepository;
use Symfony\Component\Mailer\Mailer;
use App\Repository\ProjectRepository;
use Symfony\Component\Mercure\Update;
use App\Repository\ProviderRepository;
use App\Repository\DepartmentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Mercure\Publisher;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\JsonDecode;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mailer\Bridge\Google\Smtp\GmailTransport;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage;

class ApiController extends AbstractController
{
    /**
     * @Route("/api/google-signin", name="google-Signin",  methods={"GET","HEAD", "POST" })
     */

    public function googleSignin(\Swift_Mailer $mailer ,RoleRepository $role,UserRepository $UserRepository, ?Request $request=null,UserPasswordEncoderInterface $encoder,EntityManagerInterface $em,ProjectRepository $ProjectRepository)
    {
        $API_Token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.NFCEbEEiI7zUxDU2Hj0YB71fQVT8YiQBGQWEyxWG0po';
                
        if($request!== null && $request->headers->get('JWT') == $API_Token )
        {
            $date = new DateTime();
            $CurrentTimestamp = $date->getTimestamp();
            $usernameOrEmail = $request->request->get('username');
            $password = $request->request->get('password');
            $googleSignin = $request->request->get('googleStatus');
            $accessToken =  $request->request->get('token');
            if($usernameOrEmail !=null && $password!=null && $googleSignin!=null &&  $accessToken!=null)
            {
                $client = HttpClient::create();
                $response = $client->request('GET', 'https://www.googleapis.com/oauth2/v1/tokeninfo?access_token='.$accessToken);
                $content = $response->toArray();
                $statusCode = $response->getStatusCode();
                if($statusCode!=200)
                {
                    $loadingDataStatus = 'failure';
                    $errorStatus ='wrong token data';
                    $response = new Response();
                    $response->setContent(json_encode(
        
                        [  
                            
                            'loading_data_status'=> $loadingDataStatus,
                            'error_status' => $errorStatus ,
                            
                        ]));
                    $response->headers->set('Content-Type', 'application/json');
                            
                    return $response ;
                }else{

                  
                    if($content['access_type']!=null){

                        $currentUserConnectEmail = $UserRepository->findByMail($usernameOrEmail);
                        if($currentUserConnectEmail!=[])
                        {
                            $date = new DateTime();
                            $timestamp = $date->getTimestamp();
                            $session_duration=$timestamp+3600;
                            $currentUserConnectEmail[0]->setSessionDuration($session_duration);
                           
                            $key = "alfa1";
                            $token = array(
                            "id" => $currentUserConnectEmail[0]->getId(),
                            "username" => $currentUserConnectEmail[0]->getUsername()
                            );
        
                            $jwt = JWT::encode($token, $key);
                            
                            $currentUserConnectEmail[0]->setToken($jwt);
                            $currentUserConnectEmail[0]->setIsConnect(true);
                            $em->persist($currentUserConnectEmail[0]);
                            $em->flush();
                            if($currentUserConnectEmail[0]->getProject()!=null)
                            {
                                $currentUserConnectEmail[0]->getProject()->setToken($jwt);
                                $em->persist($currentUserConnectEmail[0]);
                                $em->flush();
                                $projectStatus = true ;
                                $connectedByStatus = 'email' ;
                                $loginStatus='succes';
                                $sessionStatus = 'start';
                                $response = new Response();
                                $response->setContent(json_encode(
                                    
                                [  
                                    
                                    'project_status' => $projectStatus,
                                    'connected_by' =>  $connectedByStatus ,
                                    'token' => $jwt ,
                                    'session_status'=> $sessionStatus,
                                    'login_status' => $loginStatus,
                                    'username' => $currentUserConnectEmail[0]->getUsername(),
                                    
                                ]));
                                return $response ;
                            }else{
                                
                                $em->persist($currentUserConnectEmail[0]);
                                $em->flush();
                                $projectStatus = false ;
                                $connectedByStatus = 'email' ;
                                $loginStatus='succes';
                                $sessionStatus = 'start';
                                $response = new Response();
                                $response->setContent(json_encode(
            
                                [  
                                    
                                    'project_status' => $projectStatus,
                                    'connected_by' =>  $connectedByStatus ,
                                    'token' => $jwt ,
                                    'session_status'=> $sessionStatus,
                                    'login_status' => $loginStatus,
                                    'username' => $currentUserConnectEmail[0]->getUsername(),
                                    
                                ]));
                                return $response ;
                            }
                           
                        }else{

                            $roleString = 'ROLE_USER' ;
                            $userRole = $role->findByRoleString($roleString);
                            $user = new User;
                            $user->setUsername($usernameOrEmail);
                            $user->setEmail($usernameOrEmail);
                            $plainPassword = $password;
                            $encoded = $encoder->encodePassword($user, $plainPassword);
                            $user->setPassword($encoded);
                            $user->setRole($userRole[0]);
                            $date = new DateTime();
                            $timestamp = $date->getTimestamp();
                            $session_duration=$timestamp+3600;
                            $user->setSessionDuration($session_duration);
                            
                            $key = "alfa1";
                            $token = array(
                            
                            "username" => $usernameOrEmail
                            );
        
                            $jwt = JWT::encode($token, $key);
                            
                            $user->setToken($jwt);
                            $user->setIsConnect(true);
                            $em->persist($user);
                            $em->flush();
                            $message = (new \Swift_Message('Bienvenue sur O\'wedding'))
                            ->setFrom('O\'wedding@project.fr')
                            ->setTo($usernameOrEmail)
                            ->setBody(
                                $this->renderView(
                                    // templates/emails/registration.html.twig
                                    'api/email/registration.html.twig',
                                    ['name' => $usernameOrEmail]
                                ),
                                'text/html'
                            );

templates/api/newsletter/newsletterErrorRedirect.html.twig
{% extends 'api/base.html.twig' %}
{% block body %}

<div class="form news">
<hr>
    <h3>Oups !! une erreur est survenue</h3>
    <a href=""><button type="button" class="btn btn-info error">{{ button_label|default('Retour') }}</button></a>
<hr class="marginhr">

   
{% endblock %}

templates/api/newsletter/newsletterGuestNotFound.html.twig
{% extends 'api/base.html.twig' %}
{% block body %}

<div class="form news">
<hr>
    <h3>Vous n'avez pas de compte "invité"</h3>
    <h3>Veuillez vous rapprocher des futurs mariés</h3>
<hr class="marginhr">
</div>

   
{% endblock %}

templates/api/newsletter/newsletterResume.html.twig
{% extends 'api/base.html.twig' %}
{% block body %}

<div class="form news">
    <hr>
    <h3>Bonjour {{ guest.lastname }} {{ guest.firstname }}</h3>
       
     
    {% if  user.maried1 is defined and user.maried2 is defined %}
    <p>{{ user.maried1 }} et {{ user.maried2 }} vous remercie d'avoir remplis ce formulaire avant le {{ user.before_deadline }}</p>
        <p>Voici le récapitulatif des informations que vous avez transmis</p>
    {% endif %}     

     {% if  user.maried1 is defined and user.maried2 is not defined %}
    <p>{{ user.maried1 }}  vous remercie d'avoir remplis ce formulaire avant le {{ user.before_deadline }}</p>
        <p>Voici le récapitulatif des informations que vous avez transmis</p>
    {% endif %}  
     {% if  user.maried1 is not defined  and user.maried2 is not defined %}
    <p>{{ username }}  vous remercie d'avoir remplis ce formulaire avant le {{ before_deadline }}</p>
        <p>Voici le récapitulatif des informations que vous avez transmis</p>
    {% endif %}                       
                                            
        <hr class="marginhr">
    <div id="containerFlex">
        <div class="formbody">
            <div>
            <p>Vous avez indiqué aux futurs mariés que :</p>
            <p>- vous serez au total {{ guest.isComingWith }} personne(s).</p>

            <p>-Vous mangerez {{ guest.MeatMealNumber }} plat(s) viande(s).
            </p>
            <p>-Vous mangerez {{ guest.VegetarianMealNumber}} plat(s) végétarien(s)</p>
            </div>


            <div id="buttonFlex">
                {% if newsletter_status =='s\'abonner' %}
                
                    <a href="{{ path('change_guest_status', { id: guest_id, order:'newsletter_status', jwt:jwt } )}}"><button type="button" class="btn btn-info">Se désabonner à la newsletter</button></a>
                    
                {% endif %}

                {% if newsletter_status =='se desabonner' %}
                
                    <a href="{{ path('change_guest_status', { id: guest_id, order:'newsletter_status', jwt:jwt } )}}"><button type="button" class="btn btn-info">S'abonner à la newsletter</button></a>
                    
                {% endif %}
            </div>  
    
        </div>
        <div id="game">
        <p>Pictionnary</p>
        <div id="DrawIt">
       
			<canvas
			 id="canvas"
			/>
        </div>
        </div>
        <div id="chat">


            <style>
            

            </style>



        <div class="wrapper-message">

    <h1 id="bienvenue">Bienvenue sur le chat des invités</h1>
    <div id="conversation">
    {# {% if messages is defined %}
    {% for message in messages %}
    <div> 
    <h3>{{message.sender}}</h3>
    <p>{{message.body}}</p>
    <h6>{{message.created_at|date('d-m-Y') }}</h6>
    </div>
    {% endfor %}
    {% endif %} #}


    </div>  
    {# {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %} #}
    <div id="pre-send">

    </div>
        
        
        <form id="ui" class="ui form">
    <div class="field">
        <label></label>
        <input type="hidden" id="user-id" name="id" value="{{ username }}">
        <input id="field-name" type="hidden" name="name" value="{{ guestName  }}" placeholder="Nom">
    </div>
    <div class="field">
        <label>Message</label>
        <input id="field-message" rows="2"  placeholder="Votre message"></input>
    </div>
    <div id="buttons">
    <button class="ui button" id="sub-button" type="submit">Submit</button>
    <button class="ui button" id="reset-button" type="reset">Reset</button>
    <button class="ui button" id="clear-button" type="button">Clear messages</button>
    </div>
    <div id="connected-list">
    </div>
    </form>

    






    {% block javascripts %} 

            <script>


            const topic = "{{ username }}"
            const url = new URL('https://owedding.fr/hub');


            url.searchParams.append('topic', 'http://monsite.com/ping/'+topic);






            const eventSource = new EventSource(url);


            eventSource.onmessage = e => {
            
                console.log(e)
                
                const div =document.getElementById('conversation');
                const connect = document.getElementById('connected-list');
                const bubble = document.createElement('div');
                const message = document.createElement('p');
                const name = document.createElement('h3');
                const time = document.createElement('h6');
                newData = JSON.parse(e.data);
                console.log(newData.time);
                console.log(newData.name);
                console.log(newData.message);
                console.log(newData.remove);
                
                
                if(newData.message!=undefined && newData.name!=undefined)
                {
                    $('#pre-send').find('#'+newData.name+'').remove()
                    bubble.appendChild(name);
                    bubble.appendChild(message);
                    bubble.appendChild(time);
                    div.appendChild(bubble);
                    bubble.setAttribute('id',newData.name);
                    name.innerText= newData.name;
                    message.innerText=newData.message;
                    time.innerText=newData.hour
                    $("#conversation").scrollTop(100000000000000000000000000000000000000)
                    console.log('under the scroll')
                
                    
                }else{

                    if(newData.remove!=undefined && newData.name!=undefined && newData.message==undefined)
                    {
                        $('#pre-send').find('#'+newData.name+'').remove()
                    }else{
                
                        if(newData.name!=undefined && newData.message==undefined && newData.joined==undefined)
                        {

                        const pre_send= document.createElement('p');
                        pre_send.setAttribute('id',newData.name);
                        pre_send.innerHTML=newData.name+'&nbsp;'+'est en train d\'écrire un message'+'<p class="saving"><span>.</span><span>.</span><span>.</span></p>'
                        $('#pre-send').append(pre_send)
                        
                        
                        }

                        if(newData.name!=undefined && newData.message==undefined && newData.joined===true)
                        {
                        console.log('testshow')
                        const joined_show = document.createElement('p');
                        joined_show.setAttribute('id',newData.name);
                        joined_show.innerHTML=newData.name+'&nbsp;'+'a rejoins le chat'
                        $('#connected-list').append(joined_show)
                        window.setTimeout(()=>{
                            
                            $('#connected-list').find('#'+newData.name+'').remove();

                        },4000)
                        
                        }
                    
                    }
                        if(newData.name==undefined && newData.message==undefined && newData.anonymous===true)
                        {
                        console.log('testshow')
                        const joined_show = document.createElement('p');
                        joined_show.setAttribute('id',newData.name);
                        joined_show.innerHTML='Un anonyme a rejoins le chat'
                        $('#connected-list').append(joined_show)
                        window.setTimeout(()=>{
                            
                            $('#connected-list').find('#'+newData.name+'').remove();

                        },4000)
                        
                        }

                       if(newData.canvasData===true)
                        {
                            console.log('testcanvas:ok');
                            console.log(newData.canvas);
                            
                            const image = new Image();
                            image.src = newData.canvas;
                            image.width= 500
                            image.height= 500
                            var target =  document.getElementById('canvas').getContext('2d');
                            console.log(target);
                             
                             image.onload = function() {

                             target.drawImage(image, 0, 0);
                                console.log('image:loaded')
                                console.log(image);
                            };
                            
                        }
                                        
                }
            }

            

                
            
            
                
            
            
            
            
            
            </script>

            <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
            <script src="{{ asset('js/app.js') }}"> </script>

            <script
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}